version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-telegram_lite}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-R4m8Q2z7T1X9p6L3K5b0Wv8Yc2N4sH7}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_PREFIX=api/v1
      - DATABASE_URL=postgresql://postgres:R4m8Q2z7T1X9p6L3K5b0Wv8Yc2N4sH7@postgres:5432/telegram_lite
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=K9f3T2a8L6pQ7x4M1nV5sR0wZ8cY2b6H
      - JWT_REFRESH_SECRET=7Pq4X9m1Z5aK8t3R6L2nW0VbY4cH7sF1
      - JWT_ACCESS_EXPIRES=15m
      - JWT_REFRESH_EXPIRES=30d
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=telegram-lite
      - MINIO_USE_SSL=false
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis
      - minio

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://212.119.42.176:3001/api/v1
      - NEXT_PUBLIC_WS_URL=http://212.119.42.176:3001
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  postgres_data:
  minio_data:

